### ISSUE TITLE
Vector_search_index no longer works

### ISSUE THREAD

**Issue by digital-soul18** [DodgyBadger/GPT2DB#1]

**Comment by digital-soul18** [comment]
Copying and pasting the contents of vector_search_index.json leads to an error:
![image](https://github.com/DodgyBadger/GPT2DB/assets/7308824/82476f8c-b3bd-4911-b199-b73de48d2f54)

**Comment by DodgyBadger** [comment]
Can you provide the error message? Is the field in your database that holds the vector embeddings named title_embeddings? If it's something else, then you need to change that part of the json definition to the name of your field.

**Comment by DodgyBadger** [comment]
Looks like the syntax has changed. I did get an email recently that they were about to update Atlas. I've updated the file in the repo with the new syntax.

**Comment by digital-soul18** [comment]
Much appreciated.
